### PR TITLE
Fix schema.sql

### LINKED ISSUE #10: SQL Editor throws errors
Hi, 

Thanks for making such a great service!

When I try to follow this action:

> The schema is defined in [schema.sql](https://github.com/motifland/markprompt/blob/main/config/schema.sql). Create a Supabase database and paste the content of this file into the SQL editor. Then run the Typescript types generation script using:

Supabase throws an error: 

image

Can anyone help with what's wrong with here?

### PR DESCRIPTION
**Pull request by Taytay**
Some tables weren't created before they were altered, so I moved them to the top. Fixed missing semi-colons. 

Previously I was getting errors like: `Syntax error at or near "create"` Fixes #10

(I just realized that I also accidentally auto-formatted this, which capitalized everything, and causes the diff to be bigger than it is. Lemme know if that's okay, or if you'd prefer a smaller diff)

### CODE REVIEW

**Comment by michaelfester** [comment]
Thank you very much @Taytay for pointing this out. There were a few issues with the PR, like extra spaces in Supabase function invocations and a field that went missing (membership type), so I went ahead and applied your reordering and semicolon fixes in a separate PR (https://github.com/motifland/markprompt/pull/18), while keeping the lowercasing to keep it short, and will close this one.

What auto-formatter are you using? Happy to make the uppercase changes, but want to do it in a separate PR to keep them concise.

Again, thanks for this, much appreciated!

**Comment by Taytay** [comment]
Oh cool - I think your changes are better as they stand. I'll find out what formatted I'm using and let you know in another PR.

**Comment by michaelfester** [comment]
👍

**Comment by Taytay** [comment]
Turns out that I was using [pgFormatter](https://marketplace.visualstudio.com/items?itemName=bradymholt.pgformatter), which is a great extension, and it's using [this perl script](https://github.com/darold/pgFormatter/) under the covers.

But there's a bug in that formatting code, so I filed it here:
https://github.com/darold/pgFormatter/issues/312

I uninstalled the extension since this space just bit me pretty bad. :)

**Pull request closed without merging**
